name: build and deploy mkdocs to github pages
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip                    # install pip
          python3 -m pip install mkdocs                           # install mkdocs 
          python3 -m pip install mkdocs-git-revision-date-plugin  # install git revision date plugin
          python3 -m pip install mkdocstrings                     # install mkdocstrings
          python3 -m pip install mkdocs-material                  # install material theme
          python3 -m pip install numpy                            # install numpy
          python3 -m pip install mkdocstrings-python              # mkdocstrings python handler
      - name: Build site
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
